add raspberry pi instructions to README
mintapi/mintapi pull request #282
Opened 2021-09-18 20:12 UTC by mrooney

Addresses #281 based on multiple Discord/Github questions. I don't use Raspberry Pi so feedback is VERY welcome!

2021-09-28 23:33 UTC, jaron-l requested changes

2021-09-29 22:16 UTC, mrooney commented on README.md
> +Additionally, you may need to also link the binary to the location mintapi expects, deleting the latter file if it already exists: `ln -s /usr/bin/chromedriver /home/pi/chromedriver`
I'm honestly not sure, I just saw it in the related issue that it helped some folks, so it didn't seem like a random one-off.

2021-10-01 22:14 UTC, jaron-l commented on README.md
> +Additionally, you may need to also link the binary to the location mintapi expects, deleting the latter file if it already exists: `ln -s /usr/bin/chromedriver /home/pi/chromedriver`
Well, I think these instructions make the instructions right above it more confusing. If they follow the apt route, they won't need to manually download and add to path. How about we just change the line to something like this:

```suggestion
If you need to download the chromedriver manually, be sure to get the version that matches your chrome version and make the chromedriver available to your python interpreter either by putting the chromedriver in your python working directory or inside your `PATH` as described in the [python selenium documentation](https://www.selenium.dev/selenium/docs/api/py/index.html#drivers).
```

2021-10-06 02:00 UTC, mrooney commented on README.md
> +Additionally, you may need to also link the binary to the location mintapi expects, deleting the latter file if it already exists: `ln -s /usr/bin/chromedriver /home/pi/chromedriver`
Thanks for the great suggestion, done! Let me know if you have any other feedback :)

2021-10-06 02:34 UTC, jaron-l approved these changes

2021-10-06 12:58 UTC, merged