[FEATURE] - Add Data Format Option to CLI
mintapi/mintapi pull request #432
Opened 2022-03-29 15:09 UTC by burkematthew

Currently, the format of the output is determined based on the file extension specified.  In addition, the only available format when printing to `stdout` is json.  This PR makes a couple of enhancements:

* A new CLI option is added: `--format`.  Its valid values are `csv` and `json`, with `json` as the default answer.
* The filename no longer includes the extension.  It will be determined based on the value of `--format`.
* If no filename is specified, then the format in `stdout` is determined based on `--format`.

This PR addresses #89 .

2022-03-29 16:34 UTC, mrooney commented
Nice work! I like that it allows formatting of the non-file output and seems to clean up some areas. One thought: is there a big advantage to writing the filename automatically? I ask because it seems nice not to break existing flows if possible (folks will have to change another argument) and personally I'm a fan of having an explicit filename option versus having something change it for me. It's also nice because you might want to write to a specific location that something else is reading from that isn't looking for an extension (`/tmp/output` or whatever).

2022-03-29 16:35 UTC, mrooney requested changes
Could you also start the pending 2.0 changelog in this PR and add a note for the new flag? :)

2022-03-29 16:43 UTC, burkematthew commented
@mrooney a couple things:

1. Yes I can add the pending PR log. 
2. We are already requiring certain file extensions on output. If you don't specify csv or json, it errors out already. So this is really just changing it from evaluating the filename value for the extension type to evaluating the option. 
3. I think it could get confusing if we have both the extension and the format option. Then, we have to handle mismatched extension and format. Also, it won't technically break if they include the extension as it will just have the extension twice in the resulting filename. 

We're already introducing a decent bit of breaking changes and I think this one in particular seems a bit trivial comparatively. Unless you really object, I think we should keep it as is designed. 

Also, I'm thinking ahead a little that when we allow multiple data types in one request, we'll want to allow outputting each data type to its own file and then I think the filename functionality may have even further changes to support that.

2022-03-29 17:09 UTC, burkematthew commented
@mrooney CHANGELOG updated!

2022-03-29 18:19 UTC, mrooney commented
Thanks!

> Then, we have to handle mismatched extension and format.

If someone wants to do --format=json --filename=foo.csv that's their (weird) choice; it should be formatted as json and placed at foo.csv IMHO :P

> Also, it won't technically break if they include the extension as it will just have the extension twice in the resulting filename.

I guess I'm fine with that as long as everything can also be written to stdout the same way, so you can do something like `mintapi ... | /dev/foo`. It seems like that would be the case? I just want to avoid a use-case where you have to use a file output and want it to go to some pipe/device where appending a filename would break it. If anything that can go to a file can go to stdout, it seems still just as flexible/

2022-03-31 00:05 UTC, mrooney approved these changes

2022-03-31 00:05 UTC, merged