release 2.8 w/ MFA improvements
mintapi/mintapi pull request #541
Opened 2022-09-26 18:57 UTC by mrooney

This release contains updates for MFA UI and email.

2022-09-26 18:59 UTC, mrooney commented
@burkematthew let me know if you have any concerns about either change :) Both were handling a new change while still allowing for the old UI/behavior, and someone on Discord confirmed one of them resolved their issue, so seemed pretty safe and reasonable.

2022-09-28 00:41 UTC, burkematthew approved these changes

2022-09-28 02:47 UTC, burkematthew requested changes
Added in the update to the README for this update. Let's update the CHANGELOG as well.

2022-09-28 18:42 UTC, mrooney commented
> Added in the update to the README for this update. Let's update the CHANGELOG as well.

If I've understood you correctly, that's done! :)

2022-09-28 18:43 UTC, burkematthew approved these changes

2022-09-28 18:51 UTC, merged