Add quit_driver_on_fail flag
mintapi/mintapi pull request #561
Opened 2022-10-24 14:49 UTC by zsolteszku

Add the option to not quit the `webdriver` when an exception happens. Usecase: when there is an exception through the login process I would like to take a screenshot and save the HTML file for debugging purposes but I cannot as `Mint` always closes the driver.

2022-10-24 17:41 UTC, mrooney commented
Given the use-case, would it be more useful to provide a flag to grab a screenshot and HTML file before quitting? Is that something that can be automated?

2022-10-25 19:27 UTC, zsolteszku commented
> Given the use-case, would it be more useful to provide a flag to grab a screenshot and HTML file before quitting? Is that something that can be automated?

IMHO if the driver is passed to the Mint constructor, Mint object should not take ownership of it (like closing the driver) as the ownership probably belongs to the caller. For my usecase yes I wanted to take a screenshot but with this flag the caller can do whatever when login fails. 

I am not sure that the right approach is to support this by default, but if there is a strong preference to support it I can take a look. In terms of how easy is to support this to take a screenshot by default when there is a login problem: not that hard, need to change some chrome options about the download folder but not sure how to access the screenshot if it runs through docker.

2022-10-27 21:03 UTC, mrooney commented
Thanks, sounds good! Would you mind just adding it to the README so folks know this is an option when creating a driver?

2022-11-27 13:33 UTC, burkematthew requested changes
I second @mrooney 's request for an addition to the README. I'd also like to see this added as an option to the CLI so users that leverage that method can also use this new feature. Thanks for your contribution!

2022-12-11 17:50 UTC, burkematthew approved these changes

2022-12-11 17:51 UTC, merged